### ISSUE TITLE
Cached resources not loading on HTTPS

### ISSUE THREAD

**Issue by jtojnar** [yesodweb/yesod#1074]
Accessing the scaffolded site (tested on simple) through HTTPS, when the resource is already in browser’s cache yesod will return 304 but the resource will continue being downloaded.

![304](https://cloud.githubusercontent.com/assets/705123/9860392/32364336-5b2c-11e5-8a9c-8bd4f939faba.png)

After some time it will fail. Chrome will display the cached resources and Firefox won’t display the resources at all.

Yesod console shows different times:

    GET /
      Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
      Status: 200 OK 0.001405s
    GET /static/css/bootstrap.css
      Params: [("etag","QRP3qj9r")]
      Accept: text/css,*/*;q=0.1
      Status: 304 Not Modified 0.00007s
    GET /static/tmp/autogen-cWdljVlQ.css
      Accept: text/css,*/*;q=0.1
      Status: 304 Not Modified 0.000056s
    GET /static/tmp/autogen-SWBGXCgb.js
      Accept: */*
      Status: 304 Not Modified 0.000063s
    GET /static/fonts/glyphicons-halflings-regular.woff
      Accept: */*
      Status: 304 Not Modified 0.00007s

For comparison, here is the output of reloading with cache disabled.

![200](https://cloud.githubusercontent.com/assets/705123/9860446/847f261c-5b2c-11e5-8044-dbbf0e403184.png)

    GET /
      Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
      Status: 200 OK 0.00227s
    GET /static/css/bootstrap.css
      Params: [("etag","QRP3qj9r")]
      Accept: text/css,*/*;q=0.1
      Status: 200 OK 0.000147s
    GET /static/tmp/autogen-cWdljVlQ.css
      Accept: text/css,*/*;q=0.1
      Status: 200 OK 0.00005s
    GET /static/tmp/autogen-SWBGXCgb.js
      Accept: */*
      Status: 200 OK 0.000056s
    GET /static/fonts/glyphicons-halflings-regular.woff
      Accept: */*
      Status: 200 OK 0.000053s

**Comment by snoyberg** [comment]
Are you using warp-tls for TLS support, or some kind of reverse proxy?

**Comment by jtojnar** [comment]
No, unless it is included in unmodified simple scaffolded site.

Actually it looks like the site doesn’t have any TLS support, it is provided by yesod devel.

**Comment by snoyberg** [comment]
Did you follow the instructions from `yesod devel` about setting the APPROOT variable for accessing the https site? It should say something like:

```
If you wish to test https capabilities, you should set the following variable:
  export APPROOT=https://127.0.0.1:3443
```

**Comment by jtojnar** [comment]
Yes.

**Comment by snoyberg** [comment]
I've been unable to reproduce the problem, on my system Chrome loads up the SSL-secured version - including 304 responses - without issue.

**Comment by jtojnar** [comment]
Today I removed the ~/.stack directory and tried it again using following procedure, the problem still occurs.

```
stack new cachebug yesod-simple && cd cachebug
stack install yesod-bin cabal-install --install-ghc
stack init
stack build
export APPROOT=https://127.0.0.1:3443
stack exec -- yesod devel
```
resolver: lts-3.13 (yesod-bin 1.4.14)

Note that you will see 304 in the status column but the throbber will continue spinning. After some time (a minute apparently) it will time out and `(failed)` will replace 304s in the column.

It looks as if the connection wasn’t properly terminated.

**Comment by gregwebs** [comment]
Do you have this problem when you run your app directly rather than through yesod devel?

**Comment by jtojnar** [comment]
When running the app directly HTTPS doesn’t seem to be accessible.

**Comment by gregwebs** [comment]
I think you would need to change your `warpSettings` to use SSL. So at the moment this appears to be a devel only issue.

**Comment by sarthakbagaria** [comment]
I am facing the exact same issue. Here are the results of my current attempts at debugging:

**When the 304 response times out:**
In devel mode, and in production mode with keter settings as follows:

```
stanzas:
  - type: webapp
    exec: <path to executable>
    args: []
    hosts:
      - <prod host>
    port: 443
    requires-secure: true
    ssl: true
```

**When the 304 response does not time out:**
When I serve the static files using the static-files stanza of keter:

```
stanzas:
  - type: webapp
    exec: <path_to_executable>
    args: []
    hosts:
      - <prod_host>
    port: 443
    requires-secure: true
    ssl: true
    env:
        <static_root_env_variable>: <static_host>

 - type: static-files
    hosts:
        - <static_host>
    root: <path_to_static_folder>
    requires-secure: true
    middleware: 
        - headers:
             Access-Control-Allow-Origin: <path_to_prod_host>
```
